###
GET {{url}}/pubSub/saveData
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/pubSub/getData?key=key3
Accept: */*
Cache-Control: no-cache

### 发送消息
POST {{url}}/pubSub/sendMsg
Accept: */*
Cache-Control: no-cache
Content-Type:  application/json

{
  "topic": "channelTopic",
  "msg": {
    "id": 1000,
    "username": "一首歌的时间"
  }
}

### stream 生产消息
POST {{url}}/stream/produce?streamKey=stream-v2
Accept: */*
Cache-Control: no-cache
Content-Type:  application/json

{
  "id": 2907,
  "username": "taylor swift",
  "type": "vip"
}

### stream 消费一条 【group:consumer:  、 consumer-a 】【  group:b:consumer:   、 consumer-b】
GET {{url}}/stream/consume?groupName=group:consumer:&consumerName=consumer-a
Accept: */*
Cache-Control: no-cache

### 读取pending list
GET {{url}}/stream/getPendingList?groupName=group:b:consumer:&consumerName=consumer-b
Accept: */*
Cache-Control: no-cache